### ISSUE TITLE
I couldn't run the Web Server

### ISSUE THREAD

**Issue by alrah003** [bdtinc/maskcam#12]
I followed the instructions given in this section **[Running the MQTT Broker and Web Server](https://github.com/bdtinc/maskcam#running-the-mqtt-broker-and-web-server)** and I did all steps; however, I couldn't run the web server it gives me some errors(see the attached picture). I tried to refresh the webpage and no use. What you think I am doing wrong here? 

**FYI: I am running the web server on another laptop, not on my jetson nano. I am also using Ubuntu 20.4**

![webserver](https://user-images.githubusercontent.com/28689114/125434107-4441828e-9882-4cb3-8bde-888deeba3ffb.png)

**Comment by DonBraulio** [comment]
Hi @alrah003, did you try restarting the docker-compose environment?
