### ISSUE TITLE
RTSP Input

### ISSUE THREAD

**Issue by roysbike** [bdtinc/maskcam#13]
Can adding rtsp input ? For ipcam ?

**Comment by khalinmaxim** [comment]
@roysbike no(

**Comment by hebskjcc** [comment]
yes

**Comment by freddi-muliantono-mitrais** [comment]
> 
> 
> yes

How? I'm interested as well.

**Comment by hebskjcc** [comment]
sudo docker run --runtime nvidia --privileged --rm -it --env MASKCAM_INPUT=rtsp://user:password@172.16.3.126/h264/ch1/ --env MASKCAM_DEVICE_ADDRESS=172.16.3.25  -p 1884:1883 -p 8081:8080 -p 8555:8554 maskcam/maskcam-beta

**Comment by DonBraulio** [comment]
Thanks @hebskjcc ! I wasn't aware of that possibility.
