### ISSUE TITLE
Time is wrong in the web server report

### ISSUE THREAD

**Issue by freddi-muliantono-mitrais** [bdtinc/maskcam#14]
Hi Guys, amazing work. It's just that when I check the time visible in the web report, it's showing incorrectly. Both my web server and jetson nano are already on my timezone: GMT+7. Where can I set the timezone?

**Comment by DonBraulio** [comment]
Hey @freddi-muliantono-mitrais, since both the webserver and the jetson run on docker containers, you need to set the timezone there. I haven't tried it myself but the easiest way seems to be using the `TZ` environment variable. E.g: `--env TZ="America/New_York"`
