### ISSUE TITLE
Namespace GstRtspServer not available

### ISSUE THREAD

**Issue by ygbaldizon** [bdtinc/maskcam#16]
Hello, I tried to install the project without the Docker container as indicated in "Installing MaskCam Manually (Without a Container)" but I get the following error

**_dlinano@dlinano-desktop:~/maskcam$ python3 maskcam_run.py
Traceback (most recent call last):
  File "maskcam_run.py", line 72, in <module>
    from maskcam.maskcam_inference import main as inference_main
  File "/home/dlinano/maskcam/maskcam/maskcam_inference.py", line 41, in <module>
    gi.require_version("GstRtspServer", "1.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GstRtspServer not available_**

I'm trying to run it on the Jetson nano, the Docker Container version works fine for me.

thanks for sharing your knowledge
![Screenshot from 2021-08-25 12-50-56](https://user-images.githubusercontent.com/20074960/130840639-b7a2c62b-3a7e-40c8-abbf-2a33428d82f6.png)

**Comment by DonBraulio** [comment]
Hi @ygbaldizon,
try installing some of [these dependencies](https://github.com/bdtinc/maskcam/blob/main/Dockerfile#L72).
Most likely, you're missing the first one and/or `python-gi-dev`.
