### ISSUE TITLE
link to raw weights, facemask-yolov4-tiny_best.weights

### ISSUE THREAD

**Issue by lmarval** [bdtinc/maskcam#2]
Hello,
I want to test maskcam on Jetson Xavier NX.
Could your share the raw weights file (facemask-yolov4-tiny_best.weights,  maskcam-yolov4-best.weights?), so as to "Convert weights generated using the original darknet implementation to TRT"  (in  https://github.com/bdtinc/maskcam/blob/main/docs/Useful-Development-Scripts.md)
This seems to be a necessary procedure to test maskcam on Jetson Xavier NX.
Thank you in advance

**Comment by DonBraulio** [comment]
Hi, thanks for your interest and your question.
We've uploaded the raw weights trained with the original darknet yolo implementation, but they can be converted to pytorch or trt following the procedures here:
https://github.com/Tianxiaomo/pytorch-YOLOv4#3-darknet2onnx

The weights are now available here:
https://maskcam.s3.us-east-2.amazonaws.com/facemask-yolov4-tiny_best.weights

Check my reply here which is also related to this issue (although you shouldn't need to change any python code for this case)
https://github.com/bdtinc/maskcam/issues/3#issuecomment-846012320
