### ISSUE TITLE
Camera get purple on rstp stream

### ISSUE THREAD

**Issue by DarkZerba** [bdtinc/maskcam#7]
Hello, 
I noticed a strange bug. When I launched the rtsp stream the camera view get purple and can't recognize face anymore due to the luminosity (the camera is in front of a window). If I close my shutters the camera works perfectly. I think that you may find this interesting.  
![camera_purple](https://user-images.githubusercontent.com/38451937/120481729-b566b680-c3b0-11eb-971c-4bbd9ec02540.png)

**Comment by DonBraulio** [comment]
Hi @DarkZerba,
thanks for your comment! Unfortunately this is not something we can fix on our side, since it seems like a camera issue. Which camera is it btw?

**Comment by DarkZerba** [comment]
I didn't precise but it's only on the rtsp stream when I laucnhed via cheese for example I got no issue.
The camera is a waveshare IMX 477-160

**Comment by DonBraulio** [comment]
@EdjeElectronics any ideas? I remember you having to configure something for IMX sensors
