### ISSUE TITLE
Got an error when runing  sudo docker-compose up -d                              

### ISSUE THREAD

**Issue by AlekZen** [bdtinc/maskcam#8]
standard_init_linux.go:219: exec user process caused: exec format error                      The command '/bin/sh -c python -m pip install --upgrade pip && pip install -r requirements.txt' returned a non-zero code: 1                                                               ERROR: Service 'backend' failed to build : Build failed

**Comment by DonBraulio** [comment]
Hey @AlekZen,
Can you try rebuilding and provide more details on the command input and output, and the platform where you're trying to build the container?

**Comment by AlekZen** [comment]
I am in a jetson nano 2gb with JetPack 4.5.1, I am following the https://github.com/bdtinc/maskcam tutorial and the error appears after changing database.env data and then running <sudo docker-compose up -d> When trying to install MQTT server

**Comment by AlekZen** [comment]
![image](https://user-images.githubusercontent.com/58917719/121042736-9635a380-c779-11eb-86d8-9f5ff7dc6393.png)

**Comment by AlekZen** [comment]
![image](https://user-images.githubusercontent.com/58917719/121043132-f7f60d80-c779-11eb-9c17-82edd41c2f30.png)

**Comment by AlekZen** [comment]
![image](https://user-images.githubusercontent.com/58917719/121043222-0ba17400-c77a-11eb-92c4-1cd5670eb4a7.png)

**Comment by AlekZen** [comment]
alek@alekJetson:~/maskcam/server$ sudo docker-compose up -d
[sudo] password for alek: 
Building backend
double free or corruption (out)
SIGABRT: abort
PC=0x7f7c1634f8 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x49fb28, 0x4420047cd8, 0x29)
	/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0x9c fp=0x4420047ca0 sp=0x4420047c60
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x1fc0f420)
	github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x38 fp=0x4420047cd0 sp=0x4420047ca0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x1fc0f420)
	/build/golang-github-docker-docker-credential-helpers-iveBZG/golang-github-docker-docker-credential-helpers-0.5.0/obj-aarch64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x44 fp=0x4420047d00 sp=0x4420047cd0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x554f80, 0x44200702c0)
	/build/golang-github-docker-docker-credential-helpers-iveBZG/golang-github-docker-docker-credential-helpers-0.5.0/obj-aarch64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x1c4 fp=0x4420047da0 sp=0x4420047d00
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x57b3b8, 0x40ed60, 0x442000c001, 0x40e80c)
	<autogenerated>:4 +0x48 fp=0x4420047de0 sp=0x4420047da0
github.com/docker/docker-credential-helpers/credentials.List(0x555ac0, 0x57b3b8, 0x555000, 0x442008e008, 0x0, 0x0)
	/build/golang-github-docker-docker-credential-helpers-iveBZG/golang-github-docker-docker-credential-helpers-0.5.0/obj-aarch64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x28 fp=0x4420047e60 sp=0x4420047de0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x555ac0, 0x57b3b8, 0x7ff1174791, 0x4, 0x554fc0, 0x442008e000, 0x555000, 0x442008e008, 0x4420070250, 0x49f99c)
	/build/golang-github-docker-docker-credential-helpers-iveBZG/golang-github-docker-docker-credential-helpers-0.5.0/obj-aarch64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x12c fp=0x4420047ed0 sp=0x4420047e60
github.com/docker/docker-credential-helpers/credentials.Serve(0x555ac0, 0x57b3b8)
	/build/golang-github-docker-docker-credential-helpers-iveBZG/golang-github-docker-docker-credential-helpers-0.5.0/obj-aarch64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1a0 fp=0x4420047f50 sp=0x4420047ed0
main.main()
	/build/golang-github-docker-docker-credential-helpers-iveBZG/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x40 fp=0x4420047f80 sp=0x4420047f50
runtime.main()
	/usr/lib/go-1.8/src/runtime/proc.go:185 +0x1f4 fp=0x4420047fd0 sp=0x4420047f80
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_arm64.s:981 +0x4 fp=0x4420047fd0 sp=0x4420047fd0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_arm64.s:981 +0x4

r0      0x0
r1      0x7ff11735d8
r2      0x0
r3      0x8
r4      0x0
r5      0x7ff11735d8
r6      0xffffffffffffffff
r7      0xffffffffffffffff
r8      0x87
r9      0xffffffffffffffff
r10     0xffffffffffffffff
r11     0xffffffffffffffff
r12     0xffffffffffffffff
r13     0xffffffffffffffff
r14     0x8
r15     0x0
r16     0x54e168
r17     0x7f7c1a8838
r18     0x7f7c284a70
r19     0x7f7c283000
r20     0x6
r21     0x7f7c4c0000
r22     0x7ff1173810
r23     0x2
r24     0x7f7c283000
r25     0x1
r26     0x7f7c25a3d8
r27     0x2
r28     0x7ff1173840
r29     0x7ff11735b0
lr      0x7f7c163484
sp      0x7ff11735b0
pc      0x7f7c1634f8
fault   0x0
Sending build context to Docker daemon  108.5kB
Step 1/6 : FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
 ---> e2f19ac0b4e3
Step 2/6 : COPY ./app /app
 ---> Using cache
 ---> d3de0b722234
Step 3/6 : COPY requirements.txt /app/requirements.txt
 ---> Using cache
 ---> 5edcc65c2c77
Step 4/6 : ENV PYTHONPATH=/app
 ---> Using cache
 ---> f7eeba4f2161
Step 5/6 : WORKDIR /app
 ---> Using cache
 ---> 219bb1daf065
Step 6/6 : RUN python -m pip install --upgrade pip && pip install -r requirements.txt
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in ecd3ffd4f702
standard_init_linux.go:219: exec user process caused: exec format error
The command '/bin/sh -c python -m pip install --upgrade pip && pip install -r requirements.txt' returned a non-zero code: 1
ERROR: Service 'backend' failed to build : Build failed

**Comment by AlekZen** [comment]
![image](https://user-images.githubusercontent.com/58917719/121043747-85d1f880-c77a-11eb-8f47-993499f6ae9a.png)

**Comment by DonBraulio** [comment]
Hey @AlekZen! As mentioned in the README, this server is intended to run on another PC in your network or even a cloud instance (e.g: AWS/EC2), not in the Jetson Nano itself. Mainly because running all these containers is too much overloading for the device (even more so if it's the 2GB version), so it's not tested on that setup or any arm64 device.
Try installing the server in your personal development computer instead. Could be OSX or Linux (and probably Windows, but I haven't tested that myself).
